# Generated by Django 6.0.3 on 2026-03-12 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='marca_compativel',
            field=models.CharField(blank=True, help_text='Ex: Compatível com Scania, Volvo', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem',
            field=models.CharField(choices=[('COMPRA', 'Adquirido (Compras/Almoxarifado)'), ('DESENV_PROPRIO', 'Desenvolvimento Fundimar (Engenharia)'), ('DESENV_CLIENTE', 'Desenvolvimento sob Encomenda (Exclusivo)')], default='COMPRA', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='referencia_original',
            field=models.CharField(blank=True, help_text='Código da montadora original', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='responsavel_tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('PROJETO', 'Em Modelagem/Ferramentaria'), ('VIABILIDADE', 'Análise de Mercado'), ('ATIVO', 'Liberado para Produção/Venda'), ('OBSOLETO', 'Fora de Linha')], default='ATIVO', max_length=20),
        ),
    ]
