# Generated by Django 6.0.3 on 2026-03-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_data_cadastro_produto_marca_compativel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='marca_compativel',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='referencia_original',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='responsavel_tecnico',
        ),
        migrations.AddField(
            model_name='produto',
            name='caminho_projeto_cad',
            field=models.CharField(blank=True, max_length=500, verbose_name='Caminho CAD/Inventor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_ultima_alteracao',
            field=models.DateField(auto_now=True, verbose_name='Dt. Últ. Alt.'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ficha_processo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ficha Proc.'),
        ),
        migrations.AddField(
            model_name='produto',
            name='figuras_por_caixa',
            field=models.IntegerField(default=1, verbose_name='Figuras p/ Caixa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto_projeto',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='linha',
            field=models.CharField(choices=[('AUTOMOTIVA', 'Linha Automotiva (Pesada)'), ('AGRICOLA', 'Linha Agrícola'), ('OUTROS', 'Outros')], default='AUTOMOTIVA', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='material_ferramental',
            field=models.CharField(blank=True, max_length=50, verbose_name='Material Ferram.'),
        ),
        migrations.AddField(
            model_name='produto',
            name='material_peca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Material Peça'),
        ),
        migrations.AddField(
            model_name='produto',
            name='observacoes_tecnicas',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_bruto_amostra',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Bruto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_caixa_macho',
            field=models.CharField(blank=True, max_length=50, verbose_name='Qtde Cx Macho'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cliente_exclusivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_interno',
            field=models.CharField(max_length=50, unique=True, verbose_name='REF. MODEL'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Data Cadastro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='origem',
            field=models.CharField(choices=[('COMPRA', 'Adquirido (Compras/Almoxarifado)'), ('DESENV_PROPRIO', 'Desenvolvimento Fundimar (Engenharia)'), ('DESENV_CLIENTE', 'Desenvolvimento sob Encomenda (Exclusivo)')], default='DESENV_PROPRIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('PROJETO', 'Em Modelagem'), ('FERRAMENTARIA', 'Em Ferramentaria'), ('VIABILIDADE', 'Análise de Mercado'), ('ATIVO', 'Concluído / Produção'), ('OBSOLETO', 'Fora de Linha')], default='PROJETO', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Matéria-Prima'), ('IN', 'Insumo/Consumível'), ('PA', 'Produto Acabado'), ('MN', 'Manutenção/Uso Geral'), ('FE', 'Ferramentaria')], default='PA', max_length=2),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(default='un', max_length=10),
        ),
    ]
