# Generated by Django 6.0.3 on 2026-03-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_marca_compativel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto_projeto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='status',
        ),
        migrations.AddField(
            model_name='produto',
            name='estagio_producao',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando Início'), ('MOLDAGEM', 'Moldagem'), ('CURA', 'Cura'), ('ENVAZE', 'Envaze'), ('RESFRIAMENTO', 'Resfriamento'), ('QUEBRA_CANAL', 'Quebra de Canal'), ('REBARBACAO', 'Rebarbação'), ('JATEAMENTO', 'Jateamento'), ('CONTAGEM', 'Contagem/Inspeção'), ('ESTOQUE', 'Disponível em Estoque')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='status_projeto',
            field=models.CharField(choices=[('VIABILIDADE', 'Análise de Mercado'), ('PROJETO', 'Em Modelagem (CAD)'), ('FERRAMENTARIA', 'Em Produção (Ferramentaria/CNC)'), ('CONCLUIDO', 'Projeto Concluído'), ('OBSOLETO', 'Fora de Linha')], default='PROJETO', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='caminho_projeto_cad',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cliente_exclusivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_ultima_alteracao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ficha_processo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='figuras_por_caixa',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='observacoes_tecnicas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso_bruto_amostra',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_caixa_macho',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
