# Generated by Django 6.0.3 on 2026-03-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_foto_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='numero_projeto',
            field=models.CharField(blank=True, max_length=20, verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_teorico',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_interno',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='material_peca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Liga'),
        ),
    ]
